name: mrtk
channels:
  - conda-forge
dependencies:
  - python=3.11.7
  - pip:
      - einops==0.8.1
      - fslpy==3.23.0
      - h5py==3.14.0
      - hydra-core==1.3.2
      - matplotlib==3.10.5
      - nibabel==5.3.2
      - numpy==2.2.6
      - omegaconf==2.3.0
      - pandas==2.3.1
      - pymapvbvd==0.6.1
      - scikit-image==0.25.2
      - scipy==1.16.1
      - sigpy==0.1.27
      - tqdm==4.67.1
      - dotenv==0.9.9
